# Generated by Django 5.2.6 on 2025-09-05 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('local_businesses', '0002_notification_timeslot_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Nova Reserva'), ('booking_update', 'Atualização de Reserva'), ('review', 'Nova Avaliação'), ('plan_upgrade', 'Solicitação de Upgrade de Plano'), ('plan_upgrade_approved', 'Upgrade de Plano Aprovado'), ('plan_upgrade_rejected', 'Upgrade de Plano Rejeitado'), ('general', 'Geral')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlanUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_plan', models.CharField(choices=[('pro', 'Pro'), ('premium', 'Premium')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_upgrades', to=settings.AUTH_USER_MODEL)),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.plan')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
